[package]
name = "cat-nvim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
reqwest = "0.11.11"
scraper = "0.13.0"
tokio = { version = "1.20.1", features = ["full"] }
